version: '3'

services:
  php:
    build: .docker/php-fpm
    volumes:
      - .:/var/www/app
    ports:
      - "9000:9000"

  nginx:
    build: .docker/nginx
    volumes:
      - .:/var/www/app
    ports:
      - "1234:80"
    links:
      - php